---
version: '3'

services:

  fluentd:
    build: .
    image: index.docker.io/oaklabs/component-fluentd:${VERSION-latest}
    volumes:
      - ./fluentd.conf:/fluentd.conf:ro
      - ./gcp-credentials.json:/gcp-credentials.json:ro
