---
version: '3'

volumes:
  automatic:
services:

  fluentdfoo:
    image: fluent/fluentd:v1.3.3-1.0
    network_mode: host
    volumes:
      - ./fluentdExample.conf:/fluentd/etc/fluent.conf:ro
      - ./google-cloud-credentials.json:/etc/google/auth/application_default_credentials.json:ro
