---
version: '3'

services:

  fluentd:
    build: .
    image: index.docker.io/oaklabs/component-fluentd:${VERSION-latest}
    volumes:
      - ./config:/config:ro
      - ./secrets:/secrets:ro
    environment:
      FLUENTD_CONFIG: '/config/google-fluentd-forward.conf'
      GOOGLE_ZONE: 'us-central1-a'
      GOOGLE_APPLICATION_CREDENTIALS: '/secrets/default-credentials.json'

